name: test

on: push

jobs:
  build: # имя взято для примера
    runs-on: ubuntu-latest

    steps:
      # Клонируем репозиторий
      - uses: actions/checkout@v4
      # Устанавливаем Node.js
      - uses: actions/setup-node@v4
      # Ставим зависимости
      - name: run setup
        run: make setup
      - name: run test
        run: make test
      - name: run lint
        run: make lint
